$ANSIBLE_VAULT;1.1;AES256
36383732343337363839393837313232636134633332383231613862323065643633323235633639
6565623964643761653335333564613665626330356537330a393030336333616362356139356665
32353066623135303335333561373435303036643036613662313838663065333936326635396531
6261343137646632640a616264656362643636336461383363353664376433393963613165666633
38386161323735623435616332666534613438613133623038643765373764356237653639653339
39633362343432376431393133353730376433623931383630363666376632663934306662353061
30613931363238356166363338353535343736346638643738366364626362333366313038363333
37396133653066363237383033373238373862333836616231656466656466386335373365373663
32323234643930396631623763613661303339326135333837303662333861323435396238333831
65393330666462343937656236613361653834343638646463616163643265343637396239316635
37303734363134353732326461656365383064376232636134633237373335313264623436333930
34343939323333656135663964376334643638313264623236376330323038393935383336626333
39636635323561333137643233623739666566383134663932306564613238373633303236373664
30333638666564396137306339316132316230313465336264643537633339643430316532636438
65613762313166663031353261363230663562363261656531643566393666306633666235323262
63376531643462656565356534633430633038313266653166316230663634353038353462653866
64306133303737386435336434303130653061646234353338353263326332343765623332336461
3564313366313762393862353336383634383931386462333235
