$ANSIBLE_VAULT;1.1;AES256
64653236313232383664333064616663653936333464636233663931643635646465626130626563
3462656565313630313465646366616235353761386366320a383133363135656333333963646338
39363730353333356264353837363562346362326463366134373933373564326433313165333664
6564376263613361630a356333393634393566356331656136383736343435663163326230373664
32336461316131303739646637393034643037383365383763336330646636346666313235316661
66633435353836313735383562363239353564376233396631323134343835306533313235616134
34633061666338613433666634643236343632656136623766613463366633373661323562346661
38666562643465313261353962616330373232373732316634363965313533376232353034383733
64656164303732333830633330643738316137663934356339356332353930633937623037666335
6535343930326232343866376531653063366237323566643831
